bitcoin: true
ethereum: true
xrp: true
litecoin: true
bitcoincash: true
digibyte: true
dash: true
cardano: true
iota: true
nem: true
vertcoin: true
bitcoinsv: true
myriad: false
neo: true
tezos: true
decred: true
siacoin: true
ardor: false
dogecoin: true
ethereumclassic: false
monero: true
nano: false
qtum: false
stellar: true
zcash: true
zencash: false
